CREATE TABLE "defaults" (
    'id' BLOB PRIMARY KEY CHECK (is_uuid_v7(id)) NOT NULL,
    'salesPaymentAccount' BLOB REFERENCES 'accounts'('id'),
    'purchasePaymentAccount' BLOB REFERENCES 'accounts'('id'),
    'shipmentLocation' BLOB REFERENCES 'locations'('id'),
    'purchaseReceiptLocation' BLOB REFERENCES 'locations'('id'),
    'salesInvoiceNumberSeries' BLOB REFERENCES 'number_series'('id'),
    'purchaseInvoiceNumberSeries' BLOB REFERENCES 'number_series'('id'),
    'journalEntryNumberSeries' BLOB REFERENCES 'number_series'('id'),
    'paymentNumberSeries' BLOB REFERENCES 'number_series'('id'),
    'stockMovementNumberSeries' BLOB REFERENCES 'number_series'('id'),
    'shipmentNumberSeries' BLOB REFERENCES 'number_series'('id'),
    'purchaseReceiptNumberSeries' BLOB REFERENCES 'number_series'('id'),
    'salesQuoteNumberSeries' BLOB REFERENCES 'number_series'('id'),
    'salesInvoiceTerms' TEXT NOT NULL DEFAULT '',
    'purchaseInvoiceTerms' TEXT NOT NULL DEFAULT '',
    'shipmentTerms' TEXT NOT NULL DEFAULT '',
    'purchaseReceiptTerms' TEXT NOT NULL DEFAULT '',
    'salesQuotePrintTemplate' BLOB REFERENCES 'print_templates'('id'),
    'salesInvoicePrintTemplate' BLOB REFERENCES 'print_templates'('id'),
    'purchaseInvoicePrintTemplate' BLOB REFERENCES 'print_templates'('id'),
    'journalEntryPrintTemplate' BLOB REFERENCES 'print_templates'('id'),
    'paymentPrintTemplate' BLOB REFERENCES 'print_templates'('id'),
    'shipmentPrintTemplate' BLOB REFERENCES 'print_templates'('id'),
    'purchaseReceiptPrintTemplate' BLOB REFERENCES 'print_templates'('id'),
    'stockMovementPrintTemplate' BLOB REFERENCES 'print_templates'('id'),
    'posPrintTemplate' BLOB REFERENCES 'print_templates'('id'),
    'posCustomer' BLOB REFERENCES 'parties'('id'),
    'saveButtonColour' TEXT NOT NULL DEFAULT '',
    'cancelButtonColour' TEXT NOT NULL DEFAULT '',
    'submitButtonColour' TEXT NOT NULL DEFAULT '',
    'heldButtonColour' TEXT NOT NULL DEFAULT '',
    'returnButtonColour' TEXT NOT NULL DEFAULT '',
    'payButtonColour' TEXT NOT NULL DEFAULT '',
    'payAndPrintButtonColour' TEXT NOT NULL DEFAULT '',
    'created' TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP CHECK (datetime(created) IS NOT NULL),
    'updated' TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP CHECK (datetime(updated) IS NOT NULL)
) STRICT;