/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppManagementIndexRouteImport } from './routes/app/management/index'
import { Route as AppManagementSectionsIndexRouteImport } from './routes/app/management/sections/index'
import { Route as AppManagementProductsIndexRouteImport } from './routes/app/management/products/index'
import { Route as AppManagementPartiesIndexRouteImport } from './routes/app/management/parties/index'
import { Route as AppManagementOrder_bookersIndexRouteImport } from './routes/app/management/order_bookers/index'
import { Route as AppManagementCompaniesIndexRouteImport } from './routes/app/management/companies/index'
import { Route as AppManagementCategoriesIndexRouteImport } from './routes/app/management/categories/index'
import { Route as AppManagementAreasIndexRouteImport } from './routes/app/management/areas/index'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppManagementIndexRoute = AppManagementIndexRouteImport.update({
  id: '/app/management/',
  path: '/app/management/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppManagementSectionsIndexRoute =
  AppManagementSectionsIndexRouteImport.update({
    id: '/app/management/sections/',
    path: '/app/management/sections/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppManagementProductsIndexRoute =
  AppManagementProductsIndexRouteImport.update({
    id: '/app/management/products/',
    path: '/app/management/products/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppManagementPartiesIndexRoute =
  AppManagementPartiesIndexRouteImport.update({
    id: '/app/management/parties/',
    path: '/app/management/parties/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppManagementOrder_bookersIndexRoute =
  AppManagementOrder_bookersIndexRouteImport.update({
    id: '/app/management/order_bookers/',
    path: '/app/management/order_bookers/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppManagementCompaniesIndexRoute =
  AppManagementCompaniesIndexRouteImport.update({
    id: '/app/management/companies/',
    path: '/app/management/companies/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppManagementCategoriesIndexRoute =
  AppManagementCategoriesIndexRouteImport.update({
    id: '/app/management/categories/',
    path: '/app/management/categories/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppManagementAreasIndexRoute = AppManagementAreasIndexRouteImport.update({
  id: '/app/management/areas/',
  path: '/app/management/areas/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app/management/': typeof AppManagementIndexRoute
  '/app/management/areas/': typeof AppManagementAreasIndexRoute
  '/app/management/categories/': typeof AppManagementCategoriesIndexRoute
  '/app/management/companies/': typeof AppManagementCompaniesIndexRoute
  '/app/management/order_bookers/': typeof AppManagementOrder_bookersIndexRoute
  '/app/management/parties/': typeof AppManagementPartiesIndexRoute
  '/app/management/products/': typeof AppManagementProductsIndexRoute
  '/app/management/sections/': typeof AppManagementSectionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app/management': typeof AppManagementIndexRoute
  '/app/management/areas': typeof AppManagementAreasIndexRoute
  '/app/management/categories': typeof AppManagementCategoriesIndexRoute
  '/app/management/companies': typeof AppManagementCompaniesIndexRoute
  '/app/management/order_bookers': typeof AppManagementOrder_bookersIndexRoute
  '/app/management/parties': typeof AppManagementPartiesIndexRoute
  '/app/management/products': typeof AppManagementProductsIndexRoute
  '/app/management/sections': typeof AppManagementSectionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app/management/': typeof AppManagementIndexRoute
  '/app/management/areas/': typeof AppManagementAreasIndexRoute
  '/app/management/categories/': typeof AppManagementCategoriesIndexRoute
  '/app/management/companies/': typeof AppManagementCompaniesIndexRoute
  '/app/management/order_bookers/': typeof AppManagementOrder_bookersIndexRoute
  '/app/management/parties/': typeof AppManagementPartiesIndexRoute
  '/app/management/products/': typeof AppManagementProductsIndexRoute
  '/app/management/sections/': typeof AppManagementSectionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app/management/'
    | '/app/management/areas/'
    | '/app/management/categories/'
    | '/app/management/companies/'
    | '/app/management/order_bookers/'
    | '/app/management/parties/'
    | '/app/management/products/'
    | '/app/management/sections/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app/management'
    | '/app/management/areas'
    | '/app/management/categories'
    | '/app/management/companies'
    | '/app/management/order_bookers'
    | '/app/management/parties'
    | '/app/management/products'
    | '/app/management/sections'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app/management/'
    | '/app/management/areas/'
    | '/app/management/categories/'
    | '/app/management/companies/'
    | '/app/management/order_bookers/'
    | '/app/management/parties/'
    | '/app/management/products/'
    | '/app/management/sections/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppManagementIndexRoute: typeof AppManagementIndexRoute
  AppManagementAreasIndexRoute: typeof AppManagementAreasIndexRoute
  AppManagementCategoriesIndexRoute: typeof AppManagementCategoriesIndexRoute
  AppManagementCompaniesIndexRoute: typeof AppManagementCompaniesIndexRoute
  AppManagementOrder_bookersIndexRoute: typeof AppManagementOrder_bookersIndexRoute
  AppManagementPartiesIndexRoute: typeof AppManagementPartiesIndexRoute
  AppManagementProductsIndexRoute: typeof AppManagementProductsIndexRoute
  AppManagementSectionsIndexRoute: typeof AppManagementSectionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/management/': {
      id: '/app/management/'
      path: '/app/management'
      fullPath: '/app/management/'
      preLoaderRoute: typeof AppManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/management/sections/': {
      id: '/app/management/sections/'
      path: '/app/management/sections'
      fullPath: '/app/management/sections/'
      preLoaderRoute: typeof AppManagementSectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/management/products/': {
      id: '/app/management/products/'
      path: '/app/management/products'
      fullPath: '/app/management/products/'
      preLoaderRoute: typeof AppManagementProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/management/parties/': {
      id: '/app/management/parties/'
      path: '/app/management/parties'
      fullPath: '/app/management/parties/'
      preLoaderRoute: typeof AppManagementPartiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/management/order_bookers/': {
      id: '/app/management/order_bookers/'
      path: '/app/management/order_bookers'
      fullPath: '/app/management/order_bookers/'
      preLoaderRoute: typeof AppManagementOrder_bookersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/management/companies/': {
      id: '/app/management/companies/'
      path: '/app/management/companies'
      fullPath: '/app/management/companies/'
      preLoaderRoute: typeof AppManagementCompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/management/categories/': {
      id: '/app/management/categories/'
      path: '/app/management/categories'
      fullPath: '/app/management/categories/'
      preLoaderRoute: typeof AppManagementCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/management/areas/': {
      id: '/app/management/areas/'
      path: '/app/management/areas'
      fullPath: '/app/management/areas/'
      preLoaderRoute: typeof AppManagementAreasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppManagementIndexRoute: AppManagementIndexRoute,
  AppManagementAreasIndexRoute: AppManagementAreasIndexRoute,
  AppManagementCategoriesIndexRoute: AppManagementCategoriesIndexRoute,
  AppManagementCompaniesIndexRoute: AppManagementCompaniesIndexRoute,
  AppManagementOrder_bookersIndexRoute: AppManagementOrder_bookersIndexRoute,
  AppManagementPartiesIndexRoute: AppManagementPartiesIndexRoute,
  AppManagementProductsIndexRoute: AppManagementProductsIndexRoute,
  AppManagementSectionsIndexRoute: AppManagementSectionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
