CREATE TABLE "pricing_rules" (
    'id' BLOB PRIMARY KEY CHECK (is_uuid_v7(id)) NOT NULL,
    'numberSeries' BLOB REFERENCES 'number_series'('id'),
    'isEnabled' INTEGER NOT NULL DEFAULT 0,
    'title' TEXT NOT NULL DEFAULT '',
    'discountType' TEXT NOT NULL DEFAULT '',
    'isCouponCodeBased' INTEGER NOT NULL DEFAULT 0,
    'priority' INTEGER NOT NULL DEFAULT 0,
    'priceDiscountType' TEXT NOT NULL DEFAULT '',
    'discountRate' REAL NOT NULL DEFAULT 0,
    'discountPercentage' REAL NOT NULL DEFAULT 0,
    'discountAmount' REAL NOT NULL DEFAULT 0,
    'freeItem' BLOB REFERENCES 'items'('id'),
    'freeItemQuantity' REAL NOT NULL DEFAULT 0,
    'freeItemUnit' BLOB REFERENCES 'uoms'('id'),
    'roundFreeItemQty' INTEGER NOT NULL DEFAULT 0,
    'roundingMethod' TEXT NOT NULL DEFAULT '',
    'isRecursive' INTEGER NOT NULL DEFAULT 0,
    'recurseEvery' REAL NOT NULL DEFAULT 0,
    'minQuantity' REAL NOT NULL DEFAULT 0,
    'maxQuantity' REAL NOT NULL DEFAULT 0,
    'minAmount' REAL NOT NULL DEFAULT 0,
    'maxAmount' REAL NOT NULL DEFAULT 0,
    'validFrom' TEXT NOT NULL DEFAULT '',
    'validTo' TEXT NOT NULL DEFAULT '',
    'created' TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP CHECK (datetime(created) IS NOT NULL),
    'updated' TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP CHECK (datetime(updated) IS NOT NULL)
) STRICT;