CREATE TABLE "order_bookers" (
    'id' BLOB PRIMARY KEY CHECK (is_uuid_v7 (id)) DEFAULT (uuid_v7 ()) NOT NULL,
    'name' TEXT NOT NULL DEFAULT '',
    'phone' TEXT NOT NULL DEFAULT '',
    'created' INTEGER NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    'updated' INTEGER NOT NULL DEFAULT (CURRENT_TIMESTAMP)
) STRICT;
