CREATE TABLE "companies" (
  'id' BLOB PRIMARY KEY CHECK (is_uuid(id)) NOT NULL,
  'name' TEXT NOT NULL,
  'created' INTEGER NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  'updated' INTEGER NOT NULL DEFAULT (CURRENT_TIMESTAMP)
) STRICT;
CREATE TRIGGER update_companies_updated
AFTER
UPDATE ON companies BEGIN
UPDATE companies
SET updated = CURRENT_TIMESTAMP
WHERE id = NEW.id;
END;