CREATE TABLE "sections" (
    'id' INTEGER PRIMARY KEY NOT NULL,
    'name' TEXT NOT NULL,
    'created' TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP CHECK (datetime(created) IS NOT NULL),
    'updated' TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP CHECK (datetime(created) IS NOT NULL)
) STRICT;