CREATE TABLE "categories" (
    'id' BLOB PRIMARY KEY CHECK (is_uuid(id)) NOT NULL,
    'name' TEXT NOT NULL,
    'created' INTEGER NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    'updated' INTEGER NOT NULL DEFAULT (CURRENT_TIMESTAMP)
) STRICT;
CREATE TRIGGER update_categories_updated
AFTER
UPDATE ON categories BEGIN
UPDATE categories
SET updated = CURRENT_TIMESTAMP
WHERE id = NEW.id;
END;