CREATE TABLE transactions_report (
    id TEXT PRIMARY KEY,
    invoice TEXT,
    type TEXT,
    invoiceNo REAL,
    party TEXT,
    area TEXT,
    section TEXT,
    party_type TEXT,
    booker TEXT,
    company TEXT,
    item TEXT,
    cost_price REAL,
    price REAL,
    qty REAL,
    scheme REAL,
    discount_1 REAL,
    discount_2 REAL,
    discount_rs REAL,
    inv_d1 REAL,
    inv_d2 REAL,
    inv_drs REAL,
    total TEXT,
    net_amount TEXT,
    final_amount TEXT,
    profit TEXT,
    deleted INTEGER
);