CREATE TABLE "companies" (
  'id' BLOB PRIMARY KEY CHECK (is_uuid_v7(id)) NOT NULL,
  'name' TEXT NOT NULL,
  'created' TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP CHECK (datetime(created) IS NOT NULL),
  'updated' TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP CHECK (datetime(updated) IS NOT NULL)
) STRICT;