CREATE TABLE "users" (
    'id' BLOB PRIMARY KEY REFERENCES '_user'('id') NOT NULL,
    'email' TEXT REFERENCES '_user'('email'),
    'name' TEXT NOT NULL DEFAULT '',
    'username' TEXT UNIQUE NOT NULL DEFAULT '',
    'created' INTEGER NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    'updated' INTEGER NOT NULL DEFAULT (CURRENT_TIMESTAMP)
) STRICT;

CREATE TRIGGER update_users_updated AFTER UPDATE ON users
BEGIN
    UPDATE users SET updated = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;