CREATE TABLE "users" (
    'id' BLOB PRIMARY KEY REFERENCES '_user'('id') NOT NULL,
    'name' TEXT NOT NULL DEFAULT '',
    'username' TEXT UNIQUE NOT NULL DEFAULT '',
    'created' INTEGER NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    'updated' INTEGER NOT NULL DEFAULT (CURRENT_TIMESTAMP)
) STRICT;
