/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppManagementIndexRouteImport } from './routes/app/management/index'
import { Route as AppManagementSectionsIndexRouteImport } from './routes/app/management/sections/index'

const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppManagementIndexRoute = AppManagementIndexRouteImport.update({
  id: '/app/management/',
  path: '/app/management/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppManagementSectionsIndexRoute =
  AppManagementSectionsIndexRouteImport.update({
    id: '/app/management/sections/',
    path: '/app/management/sections/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/app/dashboard': typeof AppDashboardRoute
  '/app/management/': typeof AppManagementIndexRoute
  '/app/management/sections/': typeof AppManagementSectionsIndexRoute
}
export interface FileRoutesByTo {
  '/app/dashboard': typeof AppDashboardRoute
  '/app/management': typeof AppManagementIndexRoute
  '/app/management/sections': typeof AppManagementSectionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app/dashboard': typeof AppDashboardRoute
  '/app/management/': typeof AppManagementIndexRoute
  '/app/management/sections/': typeof AppManagementSectionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/app/dashboard' | '/app/management/' | '/app/management/sections/'
  fileRoutesByTo: FileRoutesByTo
  to: '/app/dashboard' | '/app/management' | '/app/management/sections'
  id:
    | '__root__'
    | '/app/dashboard'
    | '/app/management/'
    | '/app/management/sections/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppManagementIndexRoute: typeof AppManagementIndexRoute
  AppManagementSectionsIndexRoute: typeof AppManagementSectionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/management/': {
      id: '/app/management/'
      path: '/app/management'
      fullPath: '/app/management/'
      preLoaderRoute: typeof AppManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/management/sections/': {
      id: '/app/management/sections/'
      path: '/app/management/sections'
      fullPath: '/app/management/sections/'
      preLoaderRoute: typeof AppManagementSectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppManagementIndexRoute: AppManagementIndexRoute,
  AppManagementSectionsIndexRoute: AppManagementSectionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
