/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppManagementSectionsIndexRouteImport } from './routes/app/management/sections/index'
import { Route as AppManagementPartiesIndexRouteImport } from './routes/app/management/parties/index'
import { Route as AppManagementItemsIndexRouteImport } from './routes/app/management/items/index'
import { Route as AppManagementCategoriesIndexRouteImport } from './routes/app/management/categories/index'
import { Route as AppManagementBookersIndexRouteImport } from './routes/app/management/bookers/index'
import { Route as AppManagementAreasIndexRouteImport } from './routes/app/management/areas/index'

const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppManagementSectionsIndexRoute =
  AppManagementSectionsIndexRouteImport.update({
    id: '/app/management/sections/',
    path: '/app/management/sections/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppManagementPartiesIndexRoute =
  AppManagementPartiesIndexRouteImport.update({
    id: '/app/management/parties/',
    path: '/app/management/parties/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppManagementItemsIndexRoute = AppManagementItemsIndexRouteImport.update({
  id: '/app/management/items/',
  path: '/app/management/items/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppManagementCategoriesIndexRoute =
  AppManagementCategoriesIndexRouteImport.update({
    id: '/app/management/categories/',
    path: '/app/management/categories/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppManagementBookersIndexRoute =
  AppManagementBookersIndexRouteImport.update({
    id: '/app/management/bookers/',
    path: '/app/management/bookers/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppManagementAreasIndexRoute = AppManagementAreasIndexRouteImport.update({
  id: '/app/management/areas/',
  path: '/app/management/areas/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/app/dashboard': typeof AppDashboardRoute
  '/app/management/areas/': typeof AppManagementAreasIndexRoute
  '/app/management/bookers/': typeof AppManagementBookersIndexRoute
  '/app/management/categories/': typeof AppManagementCategoriesIndexRoute
  '/app/management/items/': typeof AppManagementItemsIndexRoute
  '/app/management/parties/': typeof AppManagementPartiesIndexRoute
  '/app/management/sections/': typeof AppManagementSectionsIndexRoute
}
export interface FileRoutesByTo {
  '/app/dashboard': typeof AppDashboardRoute
  '/app/management/areas': typeof AppManagementAreasIndexRoute
  '/app/management/bookers': typeof AppManagementBookersIndexRoute
  '/app/management/categories': typeof AppManagementCategoriesIndexRoute
  '/app/management/items': typeof AppManagementItemsIndexRoute
  '/app/management/parties': typeof AppManagementPartiesIndexRoute
  '/app/management/sections': typeof AppManagementSectionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app/dashboard': typeof AppDashboardRoute
  '/app/management/areas/': typeof AppManagementAreasIndexRoute
  '/app/management/bookers/': typeof AppManagementBookersIndexRoute
  '/app/management/categories/': typeof AppManagementCategoriesIndexRoute
  '/app/management/items/': typeof AppManagementItemsIndexRoute
  '/app/management/parties/': typeof AppManagementPartiesIndexRoute
  '/app/management/sections/': typeof AppManagementSectionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app/dashboard'
    | '/app/management/areas/'
    | '/app/management/bookers/'
    | '/app/management/categories/'
    | '/app/management/items/'
    | '/app/management/parties/'
    | '/app/management/sections/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app/dashboard'
    | '/app/management/areas'
    | '/app/management/bookers'
    | '/app/management/categories'
    | '/app/management/items'
    | '/app/management/parties'
    | '/app/management/sections'
  id:
    | '__root__'
    | '/app/dashboard'
    | '/app/management/areas/'
    | '/app/management/bookers/'
    | '/app/management/categories/'
    | '/app/management/items/'
    | '/app/management/parties/'
    | '/app/management/sections/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppManagementAreasIndexRoute: typeof AppManagementAreasIndexRoute
  AppManagementBookersIndexRoute: typeof AppManagementBookersIndexRoute
  AppManagementCategoriesIndexRoute: typeof AppManagementCategoriesIndexRoute
  AppManagementItemsIndexRoute: typeof AppManagementItemsIndexRoute
  AppManagementPartiesIndexRoute: typeof AppManagementPartiesIndexRoute
  AppManagementSectionsIndexRoute: typeof AppManagementSectionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/management/sections/': {
      id: '/app/management/sections/'
      path: '/app/management/sections'
      fullPath: '/app/management/sections/'
      preLoaderRoute: typeof AppManagementSectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/management/parties/': {
      id: '/app/management/parties/'
      path: '/app/management/parties'
      fullPath: '/app/management/parties/'
      preLoaderRoute: typeof AppManagementPartiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/management/items/': {
      id: '/app/management/items/'
      path: '/app/management/items'
      fullPath: '/app/management/items/'
      preLoaderRoute: typeof AppManagementItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/management/categories/': {
      id: '/app/management/categories/'
      path: '/app/management/categories'
      fullPath: '/app/management/categories/'
      preLoaderRoute: typeof AppManagementCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/management/bookers/': {
      id: '/app/management/bookers/'
      path: '/app/management/bookers'
      fullPath: '/app/management/bookers/'
      preLoaderRoute: typeof AppManagementBookersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/management/areas/': {
      id: '/app/management/areas/'
      path: '/app/management/areas'
      fullPath: '/app/management/areas/'
      preLoaderRoute: typeof AppManagementAreasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppManagementAreasIndexRoute: AppManagementAreasIndexRoute,
  AppManagementBookersIndexRoute: AppManagementBookersIndexRoute,
  AppManagementCategoriesIndexRoute: AppManagementCategoriesIndexRoute,
  AppManagementItemsIndexRoute: AppManagementItemsIndexRoute,
  AppManagementPartiesIndexRoute: AppManagementPartiesIndexRoute,
  AppManagementSectionsIndexRoute: AppManagementSectionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
